# Generated by Django 5.0.4 on 2024-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('s_roll', models.CharField()),
                ('s_name', models.CharField(max_length=255)),
                ('s_email', models.CharField(max_length=255)),
                ('s_phone', models.IntegerField()),
            ],
        ),
    ]
